### ISSUE TITLE
more flexible CLI; rich-click formatting

### ISSUE THREAD

**Issue by rayannott** [k4yt3x/txt2epub#1]
Thank you for a great tool -- I've been recently using it quite frequently and enjoying the simple yet functional GUI.

However, I would like to be able to use all features from the CLI as well.
Say, to specify the author and the title of the book, which I didn't find how to do in the current version.
`$ txt2epub convert -i book.txt -o book.epub -a "Max Mustermann" -t "My New Novel"`

Besides, it would probably be nice to have prettier help messages and error formatting
```shell
$ txt2epub convert
usage: txt2epub convert [-h] -i INPUT [-o OUTPUT]
txt2epub convert: error: the following arguments are required: -i/--input
```
that is why I propose using [rich-click](https://github.com/ewels/rich-click) for colored outputs.

If you agree I could open a PR with these features implemented.

---

P.S. Of course, there could be many more ideas like compiling the book when its chapters are split among a list of files and a more flexible metadata configuration:
`$ txt2epub compile --chapters my-book-directory --metadata book-info.yaml`
but this I see as secondary.

**Comment by k4yt3x** [comment]
Hi there, glad you like the program and thanks for the suggestions/PR.

The current program already has a proper help page if you do `txt2epub convert -h`:

![image](https://github.com/user-attachments/assets/54fceb9d-88f7-41ed-b061-0a0021f3d818)

I don't really want to introduce another heavy-looking dependency, so I'd rather just add more options to argparse. We can add a bit more docs to make it more clear where the help page is:

![image](https://github.com/user-attachments/assets/22ceb12e-87f5-444a-b089-00160da83fad)

I made another PR at https://github.com/k4yt3x/txt2epub/pull/3. Take a look and see if it works for you.

**Comment by k4yt3x** [comment]
>  there could be many more ideas like compiling the book when its chapters are split among a list of files and a more flexible metadata configuration

If you could send me an example book in this format I can add this support.

**Comment by k4yt3x** [comment]
I've merged the changes and released it as 1.2.0 for now. If you still like to propose further changes, feel free to keep commenting or open a new issue.

**Comment by rayannott** [comment]
> I've merged the changes and released it as 1.2.0 for now. If you still like to propose further changes, feel free to keep commenting or open a new issue.

Great thanks! This would suffice I'm sure :)

**Comment by k4yt3x** [comment]
Oh and @rayannott if you can provide a book in the format you described (split across multiple files), I can add support for it as well.

**Comment by rayannott** [comment]
Sure, here is how I imagined it:
```
├── chapters/
│   ├── chapter1.txt
│   ├── chapter2.txt
│   └── ...
├── metadata.json      # metadata (title, author, etc.); .yaml is also possible although it'd have to be another dependency
└── cover_image.jpg    # optional cover image
```

We assume once again that the first line in each file is that chapter's title.

One would then compile this into a book by executing
`$ txt2epub compile --dir ./chapters`
or something along those lines.
Should be fairly simple since you split the `.txt` file into chapters anyway, and here there would be no need for that whatsoever.

```python
# probably need to ensure the correct iteration order as well
for chapter_id, chapter_file in enumerate(pathlib.Path(chapters_directory_string).iterdir()):
    chapter_title, *chapter_content = chapter_file.read_text(encoding=ENC).split("\n")
    # proceed as you do in txt2epub.py:L56
```

Personally, I just use the one-txt-file converter at the moment but is it not a good option to have?

---
A small remark: I also noticed that one can write plain HTML in the `.txt` file (for example, I use the `<i>...</i>` tag for italic). Taking this into account, one could also add some sort of HTML code validation to warn the user, say, about a tag mismatch.

As another feature, perhaps quite a niche one, support for converting Markdown files may also be added. This way the editing experience of such a book is also facilitated by many IDEs, and the format provides an explicit TOC which I see as most useful.

**Comment by k4yt3x** [comment]
I see. Thanks for providing the info. Could you please open an issue for each feature you'd like to see added just so I can track the requests? I don't think I'll get to them quickly as I have other projects that need my attention right now, but at least this way when I see what issues I have open when I'm free I'll remember to attend to this.
